# Generated by Django 3.2.4 on 2021-06-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_comment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='audio',
            field=models.FileField(blank=True, help_text='upload audio recordings', null=True, upload_to='audio/'),
        ),
    ]
