# Generated by Django 3.2.4 on 2021-06-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='post',
            name='audio_file',
            field=models.FileField(blank=True, help_text='upload audio recordings', null=True, upload_to='audio/'),
        ),
    ]
